project_id = "cgdzjkryygwlyygeznrb"

[functions.seed-demo-users]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.resend-invite]
verify_jwt = false

[functions.notify-new-order]
verify_jwt = false

[functions.invite-account-user]
verify_jwt = false
