project_id = "cgdzjkryygwlyygeznrb"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.invite-account-user]
    verify_jwt = false
  [functions.invite-user]
    verify_jwt = false
  [functions.notify-new-order]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.resend-invite]
    verify_jwt = false
  [functions.seed-demo-users]
    verify_jwt = false
  [functions.update-user]
    verify_jwt = false
