// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-account-info.ts
import { createClient } from "npm:@supabase/supabase-js@2.91.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
function supabaseForUser(ctx) {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var get_account_info_default = defineTool({
  name: "get_account_info",
  title: "Get account info",
  description: "Return the signed-in user's Home Island account details (name, programs, co-roast tier, certification, join date, billing contact). Uses the caller's identity \u2014 no input needed.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: au, error: auErr } = await supabase.from("account_users").select("account_id, is_owner, can_place_orders, can_book_roaster").eq("user_id", userId).eq("is_active", true).maybeSingle();
    if (auErr) return { content: [{ type: "text", text: auErr.message }], isError: true };
    if (!au?.account_id) {
      return {
        content: [{ type: "text", text: "No account linked to this user." }],
        structuredContent: { account: null }
      };
    }
    const { data: account, error: accErr } = await supabase.from("accounts").select(
      "id, account_name, programs, coroast_tier, coroast_certified, coroast_joined_date, billing_contact_name, billing_email, billing_phone"
    ).eq("id", au.account_id).maybeSingle();
    if (accErr) return { content: [{ type: "text", text: accErr.message }], isError: true };
    const payload = { account, membership: au };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/list-my-orders.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@2.91.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_my_orders_default = defineTool2({
  name: "list_my_orders",
  title: "List my orders",
  description: "List recent orders visible to the signed-in user, filtered by RLS. Returns order number, status, work deadline, ship date, and totals. Ordered newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Max orders to return (1-100)."),
    status: z.enum(["DRAFT", "SUBMITTED", "CONFIRMED", "IN_PRODUCTION", "READY", "SHIPPED", "CANCELLED"]).optional().describe("Filter by order status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    let q = supabase.from("orders").select(
      "id, order_number, status, work_deadline, requested_ship_date, actual_ship_date, subtotal, total, account_id, created_at"
    ).order("created_at", { ascending: false }).limit(limit);
    if (status) q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-products.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@2.91.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    }
  );
}
var list_products_default = defineTool3({
  name: "list_products",
  title: "List products",
  description: "List products visible to the signed-in user (RLS-scoped to their account). Returns SKU, name, format, bag size, and active status.",
  inputSchema: {
    limit: z2.number().int().min(1).max(200).default(50).describe("Max products to return (1-200)."),
    active_only: z2.boolean().default(true).describe("Only return active products."),
    search: z2.string().optional().describe("Optional substring match on product name or SKU.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, active_only, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser3(ctx);
    let q = supabase.from("products").select("id, sku, product_name, format, bag_size_g, is_active, account_id, roast_group").order("product_name", { ascending: true }).limit(limit);
    if (active_only) q = q.eq("is_active", true);
    if (search && search.trim()) {
      const s = `%${search.trim()}%`;
      q = q.or(`product_name.ilike.${s},sku.ilike.${s}`);
    }
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/run-read-query.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@2.91.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var FORBIDDEN = /\b(insert|update|delete|drop|alter|create|truncate)\b/i;
function serviceClient() {
  return createClient4(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var run_read_query_default = defineTool4({
  name: "run_read_query",
  title: "Run read-only SQL query",
  description: "Execute a single read-only SQL SELECT (or WITH ... SELECT) query against the project's database and return the resulting rows. Runs with elevated permission and bypasses row-level security \u2014 intended for a trusted internal agent only. Any statement that writes or changes structure is rejected.",
  inputSchema: {
    query: z3.string().min(1).describe("A single SQL SELECT statement. No semicolons except optional trailing. No writes or DDL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false, destructiveHint: false },
  handler: async ({ query }, _ctx) => {
    const trimmed = query.trim().replace(/;+\s*$/, "");
    if (trimmed.includes(";")) {
      return { content: [{ type: "text", text: "Error: multiple statements are not allowed." }], isError: true };
    }
    const lowered = trimmed.toLowerCase();
    if (!lowered.startsWith("select") && !lowered.startsWith("with")) {
      return { content: [{ type: "text", text: "Error: only SELECT (or WITH ... SELECT) queries are allowed." }], isError: true };
    }
    if (FORBIDDEN.test(lowered)) {
      return { content: [{ type: "text", text: "Error: query contains a forbidden keyword." }], isError: true };
    }
    const supabase = serviceClient();
    const { data, error } = await supabase.rpc("mcp_run_read_sql", { query_text: trimmed });
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = Array.isArray(data) ? data : [];
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { rows, row_count: rows.length }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "cgdzjkryygwlyygeznrb";
var mcp_default = defineMcp({
  name: "home-island-mcp",
  title: "Home Island Coffee Partners",
  version: "0.1.0",
  instructions: "Tools for the Home Island Coffee Partners platform. Read-only access to the signed-in user's account details, orders, and products. All data is scoped to the caller by row-level security.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_account_info_default, list_my_orders_default, list_products_default, run_read_query_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
