import React, { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { useNavigate } from 'react-router-dom';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/contexts/AuthContext';
import { toast } from 'sonner';
import type { GrindOption, DeliveryMethod } from '@/types/database';

interface LineItem {
  productId: string;
  productName: string;
  quantity: number;
  grind: GrindOption | null;
  grindOptions: GrindOption[];
  price: number | null;
}

export default function NewOrder() {
  const { authUser } = useAuth();
  const navigate = useNavigate();
  const queryClient = useQueryClient();

  const [lineItems, setLineItems] = useState<LineItem[]>([]);
  const [requestedShipDate, setRequestedShipDate] = useState('');
  const [deliveryMethod, setDeliveryMethod] = useState<DeliveryMethod>('PICKUP');
  const [clientPo, setClientPo] = useState('');
  const [clientNotes, setClientNotes] = useState('');
  const [submitting, setSubmitting] = useState(false);

  // Fetch products for this client (RLS filters automatically)
  const { data: products, isLoading: productsLoading } = useQuery({
    queryKey: ['client-products'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('products')
        .select('id, product_name, sku, bag_size_g, format, grind_options')
        .eq('is_active', true)
        .order('product_name', { ascending: true });

      if (error) throw error;
      return data ?? [];
    },
  });

  // Fetch current prices for all products
  const { data: prices } = useQuery({
    queryKey: ['client-prices'],
    queryFn: async () => {
      const { data, error } = await supabase
        .from('price_list')
        .select('product_id, unit_price, effective_date')
        .order('effective_date', { ascending: false });

      if (error) throw error;

      // Build map of product_id -> latest price
      const priceMap: Record<string, number> = {};
      for (const p of data ?? []) {
        if (!priceMap[p.product_id]) {
          priceMap[p.product_id] = p.unit_price;
        }
      }
      return priceMap;
    },
  });

  const addProduct = (productId: string) => {
    const product = products?.find((p) => p.id === productId);
    if (!product) return;
    if (lineItems.some((li) => li.productId === productId)) {
      toast.error('Product already added');
      return;
    }

    const grindOpts = (product.grind_options ?? []) as GrindOption[];
    setLineItems([
      ...lineItems,
      {
        productId: product.id,
        productName: product.product_name,
        quantity: 1,
        grind: grindOpts.length > 0 ? grindOpts[0] : null,
        grindOptions: grindOpts,
        price: prices?.[product.id] ?? null,
      },
    ]);
  };

  const updateQuantity = (productId: string, qty: number) => {
    setLineItems((prev) =>
      prev.map((li) => (li.productId === productId ? { ...li, quantity: Math.max(1, qty) } : li))
    );
  };

  const updateGrind = (productId: string, grind: GrindOption) => {
    setLineItems((prev) =>
      prev.map((li) => (li.productId === productId ? { ...li, grind } : li))
    );
  };

  const removeLine = (productId: string) => {
    setLineItems((prev) => prev.filter((li) => li.productId !== productId));
  };

  const submitOrder = async () => {
    if (!authUser?.clientId) {
      toast.error('No client linked to your account');
      return;
    }
    if (lineItems.length === 0) {
      toast.error('Add at least one product');
      return;
    }

    // Check all items have prices
    const missingPrice = lineItems.find((li) => li.price === null);
    if (missingPrice) {
      toast.error(`No price found for "${missingPrice.productName}". Contact support.`);
      return;
    }

    setSubmitting(true);
    try {
      // Create order (order_number is auto-generated by DB trigger)
      const { data: order, error: orderError } = await supabase
        .from('orders')
        .insert({
          client_id: authUser.clientId,
          order_number: '', // Trigger will replace with auto-generated value
          status: 'SUBMITTED',
          requested_ship_date: requestedShipDate || null,
          delivery_method: deliveryMethod,
          client_po: clientPo || null,
          client_notes: clientNotes || null,
          created_by_user_id: authUser.id,
        })
        .select('id, order_number')
        .single();

      if (orderError) throw orderError;

      // Create line items
      const lineItemsData = lineItems.map((li) => ({
        order_id: order.id,
        product_id: li.productId,
        quantity_units: li.quantity,
        grind: li.grind,
        unit_price_locked: li.price!,
      }));

      const { error: lineError } = await supabase.from('order_line_items').insert(lineItemsData);
      if (lineError) throw lineError;

      toast.success(`Order ${order.order_number} submitted!`);
      queryClient.invalidateQueries({ queryKey: ['orders'] });
      navigate('/portal/orders');
    } catch (err) {
      console.error('Submit error:', err);
      toast.error('Failed to submit order');
    } finally {
      setSubmitting(false);
    }
  };

  const availableProducts = products?.filter((p) => !lineItems.some((li) => li.productId === p.id)) ?? [];

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">New Order</h1>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Product Selection */}
        <Card>
          <CardHeader><CardTitle>Add Products</CardTitle></CardHeader>
          <CardContent>
            {productsLoading ? (
              <p className="text-muted-foreground">Loading…</p>
            ) : availableProducts.length === 0 ? (
              <p className="text-muted-foreground">All products added or none available.</p>
            ) : (
              <ul className="space-y-2">
                {availableProducts.map((p) => (
                  <li key={p.id} className="flex items-center justify-between border-b pb-2 last:border-0">
                    <div>
                      <span className="font-medium">{p.product_name}</span>
                      <span className="ml-2 text-xs text-muted-foreground">{p.bag_size_g}g</span>
                      {prices?.[p.id] ? (
                        <span className="ml-2 text-sm text-muted-foreground">${prices[p.id].toFixed(2)}</span>
                      ) : (
                        <span className="ml-2 text-xs text-destructive">No price</span>
                      )}
                    </div>
                    <Button size="sm" variant="outline" onClick={() => addProduct(p.id)}>Add</Button>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Order Details */}
        <Card>
          <CardHeader><CardTitle>Order Details</CardTitle></CardHeader>
          <CardContent className="space-y-4">
            <div>
              <Label htmlFor="shipDate">Requested Ship Date</Label>
              <Input
                id="shipDate"
                type="date"
                value={requestedShipDate}
                onChange={(e) => setRequestedShipDate(e.target.value)}
              />
            </div>
            <div>
              <Label htmlFor="delivery">Delivery Method</Label>
              <Select value={deliveryMethod} onValueChange={(v) => setDeliveryMethod(v as DeliveryMethod)}>
                <SelectTrigger id="delivery">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="PICKUP">Pickup</SelectItem>
                  <SelectItem value="DELIVERY">Delivery</SelectItem>
                  <SelectItem value="COURIER">Courier</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div>
              <Label htmlFor="po">PO Number (optional)</Label>
              <Input id="po" value={clientPo} onChange={(e) => setClientPo(e.target.value)} />
            </div>
            <div>
              <Label htmlFor="notes">Notes (optional)</Label>
              <Textarea id="notes" value={clientNotes} onChange={(e) => setClientNotes(e.target.value)} rows={3} />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Line Items */}
      <Card className="mt-6">
        <CardHeader><CardTitle>Line Items ({lineItems.length})</CardTitle></CardHeader>
        <CardContent>
          {lineItems.length === 0 ? (
            <p className="text-muted-foreground">No products selected yet.</p>
          ) : (
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b text-left">
                  <th className="pb-2">Product</th>
                  <th className="pb-2">Qty</th>
                  <th className="pb-2">Grind</th>
                  <th className="pb-2">Price</th>
                  <th className="pb-2"></th>
                </tr>
              </thead>
              <tbody>
                {lineItems.map((li) => (
                  <tr key={li.productId} className="border-b last:border-0">
                    <td className="py-2">{li.productName}</td>
                    <td className="py-2">
                      <Input
                        type="number"
                        min={1}
                        className="w-20"
                        value={li.quantity}
                        onChange={(e) => updateQuantity(li.productId, parseInt(e.target.value) || 1)}
                      />
                    </td>
                    <td className="py-2">
                      {li.grindOptions.length > 0 ? (
                        <Select value={li.grind ?? ''} onValueChange={(v) => updateGrind(li.productId, v as GrindOption)}>
                          <SelectTrigger className="w-32">
                            <SelectValue />
                          </SelectTrigger>
                          <SelectContent>
                            {li.grindOptions.map((g) => (
                              <SelectItem key={g} value={g}>{g}</SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      ) : (
                        <span className="text-muted-foreground">—</span>
                      )}
                    </td>
                    <td className="py-2">
                      {li.price !== null ? `$${li.price.toFixed(2)}` : <span className="text-destructive">No price</span>}
                    </td>
                    <td className="py-2">
                      <Button size="sm" variant="ghost" onClick={() => removeLine(li.productId)}>Remove</Button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}

          <div className="mt-6 flex justify-end">
            <Button onClick={submitOrder} disabled={submitting || lineItems.length === 0}>
              {submitting ? 'Submitting…' : 'Submit Order'}
            </Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
